version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Build package
          command: |
            cargo package
  publish:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - run:
          name: Publish package
          command: |
            cargo login $CRATES_KEY
            cargo publish  

workflows:
  version: 2
  build_publish:
    jobs:
      - build
          filters:
            tags:
              only: /^v.*/      
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/            